apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: app-pvc
  containers:
  - name: app
    image: nginx:1.25
    volumeMounts:
    - name: app-storage
      mountPath: /data

