apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
  labels:
    pattern: sidecar
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: app
    image: nginx:1.25
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  - name: log-shipper
    image: busybox
    command: ["/bin/sh", "-c", "tail -n+1 -F /logs/access.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /logs

